# # Couldn't automatically generate a config from your source code.
# # This is a generic template to serve as a base for your custom config
# # See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    macos:
      xcode: 15.2.0

    steps:
      # Commands will execute in macOS container
      # with Xcode 14.2.0 installed
      - run: git clone --depth=1 --branch=master https://github.com/openframeworks/openFrameworks
      - run: cd apps
      - checkout
      - run: cd example_HelloLaser
      - run: rm bin/stdin.log bin/stdout.log bin/stderr.log
      - run: xcodebuild -scheme "example_HelloLaser Debug" build && open bin/example_HelloLaserDebug.app -i bin/stdin.log -o bin/stdout.log --stderr bin/stderr.log
# jobs:
#   test:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       # Replace this with a real test runner invocation
#       - run:
#           name: Run tests
#           command: echo 'replace me with real tests!' && false
#   build:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       # Replace this with steps to build a package, or executable
#       - run:
#           name: Build an artifact
#           command: touch example.txt
#       - store_artifacts:
#           path: example.txt
#   deploy:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       # Replace this with steps to deploy to users
#       - run:
#           name: deploy
#           command: '#e.g. ./deploy.sh'
# workflows:
#   example:
#     jobs:
#       - test
#       - build:
#           requires:
#             - test
#       - deploy:
#           requires:
#             - test
