name: build-linux-arm

# make the action not run on the local repo if the branch is also in a pull request to OF/OF
on: [push]

env:
  ccache: ccache

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux-arm-platforms:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          cfg:
          - {target: linuxarmv6l, libs: armv6l}
          - {target: linuxaarch64, libs: aarch64}
    env:
     TARGET: ${{matrix.cfg.target}}
    steps:
    - name: Cache Packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make curl libunwind-dev libjack-jackd2-0 libjack-jackd2-dev freeglut3-dev libasound2-dev libxmu-dev libxxf86vm-dev g++ libgl1-mesa-dev libglu1-mesa-dev libraw1394-dev libudev-dev libdrm-dev libglew-dev libopenal-dev libsndfile1-dev libfreeimage-dev libcairo2-dev libfreetype6-dev libssl-dev libpulse-dev libusb-1.0-0-dev libgtk2.0-dev libopencv-dev libassimp-dev librtaudio-dev gdb libglfw3-dev liburiparser-dev libcurl4-openssl-dev libpugixml-dev libgconf-2-4 libgtk2.0-0 libpoco-dev libxcursor-dev libxi-dev libxinerama-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-libav gstreamer1.0-pulseaudio gstreamer1.0-x gstreamer1.0-plugins-bad gstreamer1.0-alsa gstreamer1.0-plugins-base gstreamer1.0-plugins-good
        version: 1.0

    - name: checkout openframeworks
      uses: actions/checkout@v4
      with:
        repository: openframeworks/openFrameworks
    # now we add in ofxLaser as addon
    - name: checkout ofxLaser
      uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/addons/ofxLaser
    # and here we replace the empty example with the hello laser example
    - name: remove emptyExample
      run: rm -r ${{ github.workspace }}/examples/templates/emptyExample
    - name: replace emptyExample with example_HelloLaser
      run: cp -r ${{ github.workspace }}/addons/ofxLaser/example_HelloLaser ${{ github.workspace }}/examples/templates/emptyExample

    # continue openframeworks defined pipeline
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.12
      with:
        # key: ${{ matrix.os }}-${{ matrix.type }}
        key: ${{ matrix.cfg.target }}
    - name: Download libs
      run: ./scripts/linux/download_libs.sh -a ${{matrix.cfg.libs}};
    - name: Install dependencies
      run: ./scripts/ci/$TARGET/install.sh;
    - name: Build
      run: ./scripts/ci/$TARGET/build.sh;
